-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- A collection of Annotations & Class definitions
-- ===================================================================================

--- @class Time a time value in Seconds
--- @class EntityId the id of an entity
--- @class Yaw Yaw Rotation
--- @class Pitch Pitch Rotation
--- @class Vector3 a 3 dimensional vector table