-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- Generated by CryMP-Server.exe(v23) Build MSVC 19.29.30159.0
-- This file Contains data which will be loaded into the 'SavedUsers' Key 
-- for the 'AccessHandler' Server Component 
-- ===================================================================================
return {
 ["1073450"] = {
  ["AccessLevel"] = 9,
  ["NameProtected"] = true,
  ["Name"] = "shortcut0",
  ["ProfileID"] = "1073450",
 },
 ["1"] = {
  ["AccessLevel"] = 9,
  ["NameProtected"] = true,
  ["Name"] = "protected_name",
  ["ProfileID"] = "1",
 },
 ["1073103"] = {
  ["AccessLevel"] = 9,
  ["NameProtected"] = true,
  ["Name"] = "shortcut0",
  ["ProfileID"] = "1073103",
 },
 ["127.0.0.1"] = {
  ["AccessLevel"] = 9,
  ["NameProtected"] = true,
  ["Name"] = "shortcut0",
  ["ProfileID"] = "127.0.0.1",
 },
}