-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- Generated by CryMP-Server.exe(v21) Build MSVC 19.29.30159.0
-- This file Contains data which will be loaded into the 'PlayerData' Key for the 'ActorHandler' 
-- Server Component 
-- ===================================================================================
return {
 ["1073246"] = {
  ["LastConnect"] = 1754954980,
  ["FirstBloodScored"] = 0,
  ["ServerTime"] = 2561,
  ["LastName"] = "Nomad(1)",
 },
 ["1073194"] = {
  ["LastConnect"] = 1754805460,
  ["ServerTime"] = 1669,
 },
 ["1073219"] = {
  ["LastConnect"] = 1754924133,
  ["ServerTime"] = 16403,
 },
 ["ip0"] = {
  ["LastConnect"] = 1754953259,
  ["ServerTime"] = 4193,
 },
 ["1073216"] = {
  ["LastConnect"] = 1754852961,
  ["ServerTime"] = 1906,
 },
 ["1073245"] = {
  ["LastConnect"] = 1754954810,
  ["FirstBloodScored"] = 7,
  ["ServerTime"] = 1060,
 },
 ["1073247"] = {
  ["LastConnect"] = 1754966696,
  ["FirstBloodScored"] = 40,
  ["ServerTime"] = 9619,
 },
 ["1073218"] = {
  ["LastConnect"] = 1754924133,
  ["ServerTime"] = 14948,
 },
 ["1073248"] = {
  ["LastConnect"] = 1754966696,
  ["FirstBloodScored"] = 1,
  ["ServerTime"] = 6938,
 },
 ["1073215"] = {
  ["LastConnect"] = 1754852017,
  ["ServerTime"] = 1735,
 },
}