-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- Generated by CryMP-Server.exe(v21) Build MSVC 19.29.30159.0
-- This file Contains data which will be loaded into the 'PlayerData' Key 
-- for the 'ActorHandler' Server Component 
-- ===================================================================================
return {
 ["1073353"] = {
  ["LastConnect"] = 1755305344,
  ["FirstBloodScored"] = 3,
  ["ServerTime"] = 2153,
  ["Rank"] = {
   ["Name"] = "COPPER II",
   ["RankXP"] = 1215,
   ["RankStage"] = 2,
   ["Rank"] = 4,
   ["NextRankXP"] = 1425,
  },
 },
 ["1073374"] = {
  ["LastConnect"] = 1755355603,
  ["FirstBloodScored"] = 0,
  ["ServerTime"] = 807,
 },
 ["1073450"] = {
  ["LastConnect"] = 1755570599,
  ["LastCMId"] = 16,
  ["FirstBloodScored"] = 0,
  ["ServerTime"] = 4205,
  ["Rank"] = {
   ["Name"] = "PLASTIC II",
   ["RankXP"] = 186,
   ["RankStage"] = 2,
   ["NextRankXP"] = 225,
  },
 },
 ["1073372"] = {
  ["LastConnect"] = 1755349433,
  ["FirstBloodScored"] = 0,
  ["ServerTime"] = 102,
 },
 ["1073351"] = {
  ["LastConnect"] = 1755556620,
  ["FirstBloodScored"] = 0,
  ["ServerTime"] = 19665,
  ["Rank"] = {
   ["RankXP"] = 80,
   ["RankStage"] = 1,
   ["Name"] = "PLASTIC I",
   ["NextRankXP"] = 150,
  },
 },
 ["ip10001"] = {
  ["LastConnect"] = 1755566288,
  ["ServerTime"] = 2955,
  ["FirstBloodScored"] = 0,
  ["LastCMId"] = 3,
  ["Rank"] = {
   ["Name"] = "PLASTIC I",
   ["RankXP"] = 69,
  },
 },
}