-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- Generated by CryMP-Server.exe(v21) Build MSVC 19.29.30159.0
-- This file Contains data which will be loaded into the 'PlayerData' Key 
-- for the 'ActorHandler' Server Component 
-- ===================================================================================
return {
 ["1073353"] = {
  ["LastConnect"] = 1755305344,
  ["FirstBloodScored"] = 3,
  ["ServerTime"] = 2153,
  ["Rank"] = {
   ["Name"] = "COPPER II",
   ["RankXP"] = 1215,
   ["RankStage"] = 2,
   ["Rank"] = 4,
   ["NextRankXP"] = 1425,
  },
 },
}