-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- Generated by CryMP-Server.exe(v21) Build MSVC 19.29.30159.0
-- This file Contains data which will be loaded into the 'SavedGeoData' Key for the 'Network' 
-- Server Component 
-- ===================================================================================
return {
 ["148.222.205.147"] = {
  ["CountryCode"] = "CL",
  ["AS"] = "AS14593 Space Exploration Technologies Corporation",
  ["CountryName"] = "Chile",
  ["Timezone"] = "America/Santiago",
  ["ContinentName"] = "South America",
  ["City"] = "Santiago",
  ["RegionName"] = "Santiago Metropolitan",
  ["Organisation"] = "Starlink Chile SpA",
  ["District"] = "",
  ["ISP"] = "SpaceX Starlink",
  ["ContinentCode"] = "SA",
 },
}