-- ===================================================================================
--          ____            __  __ ____            ____                             --
--         / ___|_ __ _   _|  \/  |  _ \          / ___|  ___ _ ____   _____ _ __   --
--        | |   | '__| | | | |\/| | |_) |  _____  \___ \ / _ \ '__\ \ / / _ \ '__|  --
--        | |___| |  | |_| | |  | |  __/  |_____|  ___) |  __/ |   \ V /  __/ |     --
--         \____|_|   \__, |_|  |_|_|             |____/ \___|_|    \_/ \___|_|     --
--                    |___/          by: shortcut0                                  --
-- Generated by CryMP-Server.exe(v21) Build MSVC 19.29.30159.0
-- This file Contains data which will be loaded into the 'Statistics' Key 
-- for the 'Statistics' Server Component 
-- ===================================================================================
return {
 ["PlayerRecord"] = 2,
 ["ClientDataTransferred"] = 1864978,
 ["ServerLifetime"] = 119362,
 ["TotalWallJumps"] = 370,
 ["ChatCommandsUsed"] = 4662,
 ["ChannelCount"] = 324,
 ["ChannelRecord"] = 45,
}